// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uzoma.Api.Data;

#nullable disable

namespace Uzoma.Api.Migrations
{
    [DbContext(typeof(UzomaDbContext))]
    [Migration("20260107001602_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uzoma.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "T-Shirts",
                            CreatedAt = new DateTime(2026, 1, 7, 0, 16, 1, 455, DateTimeKind.Utc).AddTicks(8247),
                            Description = "100% cotton, available in all sizes",
                            ImageUrl = "https://example.com/images/classic-tshirt.jpg",
                            Name = "Classic T-Shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Jeans",
                            CreatedAt = new DateTime(2026, 1, 7, 0, 16, 1, 455, DateTimeKind.Utc).AddTicks(8711),
                            Description = "Denim, slim fit style",
                            ImageUrl = "https://example.com/images/slim-fit-jeans.jpg",
                            Name = "Slim Fit Jeans",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Jackets",
                            CreatedAt = new DateTime(2026, 1, 7, 0, 16, 1, 455, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Genuine leather, stylish",
                            ImageUrl = "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=436&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Leather Jacket",
                            Price = 199.99m
                        });
                });

            modelBuilder.Entity("Uzoma.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
